version: '2'
services:
    quintaneros-app:
        image: quintaneros
        external_links:
            - quintaneros-postgresql:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/quintaneros
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    quintaneros-postgresql:
        extends:
            file: postgresql.yml
            service: quintaneros-postgresql
